### ISSUE TITLE
Update Traefik recipe to v2

### ISSUE THREAD

**Issue by funkypenguin** [geek-cookbook/geek-cookbook#165]
It's been long enough. Let's upgrade the Traefik recipe to v2 ;)

**Comment by Etzeitet** [comment]
Hello

I was going to raise an issue regarding the current V2 instructions for Traefik. Since this issue was recently opened I figured I'd add it here.

I followed the steps [here](https://geek-cookbook.funkypenguin.co.nz/ha-docker-swarm/traefik/) but kept running into issues with the Let's Encrypt generation of certificates using DNS-01 (with CloudFlare). The upshot is that the instructions have you create a stack with multiple instances of Traefik (global deployment on all Manager Nodes), which Traefik/LetsEncrypt doesn't like.

Spinning up a single instance of Traefik and everything works. I found someone with a similar issue and some responses:

https://community.traefik.io/t/multiple-traefik-instances-using-same-letsencrypt-domain-fails-to-create-certs/6758

You'll note also that the documentation explicitly states that the `acme.json` file should *not* be shared between instances.

An initial idea I had, but haven't tried, is to create additional Traefik instances that use static certificates and point to the one created by the "main" Traefik instance. Though this opens up questions on how you deploy the instances to the correct nodes, as I'm not aware of any way of saying "don't deploy Service A on Node, if Service X is running".

Another issue I ran into is the the use of the env file:

```
env_file: /var/data/config/traefikv2/traefikv2.env
```

Your YAML includes it, but the instructions don't make any mention of it. This will cause an error when trying to deploy if the file doesn't exist. It may be worth a note to say the file should exist. Incidentally, it is where I put my token details for the CloudFlare API.
